language: node_js
node_js:
  - "node"

sudo: false

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 1 # give xvfb some time to start

notifications:
  slack:
    rooms:
      gorlifsense:S7RWHqp3eUYiYBusZOzXytvR#development
    on_success: change
