language: node_js
node_js:
  - "~6.9"
  - "8"

cache: yarn

sudo: required
dist: trusty

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

notifications:
  slack:
    rooms:
      gorlifsense:S7RWHqp3eUYiYBusZOzXytvR#boardgamesresults
    on_success: change
